import './globals.css'
import { IBM_Plex_Sans } from 'next/font/google'

const plex = IBM_Plex_Sans({ subsets: ['latin'], weight: ['300', '400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plex.className}>{children}</body>
    </html>
  )
}
